# Generated by Django 5.2 on 2025-04-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('CPF', models.CharField(max_length=15)),
                ('genero', models.CharField(max_length=15)),
                ('estado_civil', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.PositiveBigIntegerField(max_length=100)),
                ('complemento', models.CharField(choices=[('CASA', 'Casa'), ('APTO', 'Apartamento'), ('SALA', 'Sala'), ('OUTRO', 'Outro')], max_length=15, null=True)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('CEP', models.CharField(default='00000000', max_length=10)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
